author: greatman
database: true
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.greatman.plugins.inn.Inn
name: Inn
startup: postworld
version: 0.2
commands:
    inn:
        description: inn command
        usage: /inn
permissions:
    inn.*:
        description: Gives access to all inn commands
        children:
            inn.bypass: true
            inn.create: true
    inn.create:
        description: Allow people to create a Inn door
        default: true
    inn.bypass:
        description: Allow people to bypass door payment
        default: false